return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  branch = "main",
  build = ":TSUpdate",
  install = {
    "astro",
    "bash",
    "c",
    "comment",
    "cmake",
    "css",
    "csv",
    "diff",
    "dockerfile",
    "editorconfig",
    -- "elixir",
    "graphql",
    -- "heex",
    "html",
    "javascript",
    "jq",
    "json",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "nix",
    -- "norg",
    "prisma",
    "query",
    "regex",
    "rust",
    "sql",
    "ssh_config",
    "toml",
    "tsx",
    "typescript",
    "typst",
    "vim",
    "vimdoc",
    "yaml",
    "zig",
  },
  -- opts = {},
}

-- return {
--   "nvim-treesitter/nvim-treesitter",
--   build = ":TSUpdate",
--   lazy = false,
--   main = "nvim-treesitter.configs",
--   opts = {
--     ensure_installed = {
--       "astro",
--       "bash",
--       "c",
--       "comment",
--       "cmake",
--       "css",
--       "csv",
--       "diff",
--       "dockerfile",
--       "editorconfig",
--       -- "elixir",
--       "graphql",
--       -- "heex",
--       "html",
--       "javascript",
--       "jq",
--       "json",
--       "latex",
--       "lua",
--       "markdown",
--       "markdown_inline",
--       "nix",
--       -- "norg",
--       "prisma",
--       "query",
--       "regex",
--       "rust",
--       "sql",
--       "ssh_config",
--       "toml",
--       "tsx",
--       "typescript",
--       "typst",
--       "vim",
--       "vimdoc",
--       "yaml",
--       "zig",
--     },
--     auto_install = true,
--     highlight = {
--       enable = true,
--       additional_vim_regex_highlighting = false,
--     },
--     indent = { enable = true },
--     -- textobjects = {
--     --   select = {
--     --     enable = true,
--     --     keymaps = {
--     --       ["aa"] = "@parameter.outer",
--     --       ["ia"] = "@parameter.inner",
--     --       ["af"] = "@function.outer",
--     --       ["if"] = "@function.inner",
--     --       ["ac"] = "@class.outer",
--     --       ["ic"] = "@class.inner",
--     --     },
--     --   },
--     --   swap = {
--     --     enable = true,
--     --     swap_next = { ["<leader>sa"] = "@parameter.inner" },
--     --     swap_previous = { ["<leader>sA"] = "@parameter.inner" },
--     --   },
--     --   lsp_interop = {
--     --     enable = true,
--     --     border = "none",
--     --     floating_preview_opts = {},
--     --     peek_definition_code = {
--     --       ["<leader>df"] = "@function.outer",
--     --       ["<leader>dF"] = "@class.outer",
--     --     },
--     --   },
--     -- },
--   },
--   -- There are additional nvim-treesitter modules that you can use to interact
--   -- with nvim-treesitter. You should go explore a few and see what interests you:
--   --
--   --    - Incremental selection: Included, see `:help nvim-treesitter-incremental-selection-mod`
--   --    - Show your current context: https://github.com/nvim-treesitter/nvim-treesitter-context
--   --    - Treesitter + textobjects: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
-- }
